# Generated by Django 5.0.2 on 2024-03-04 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('musician', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='albumModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_name', models.CharField(max_length=100)),
                ('album_release_date', models.DateField()),
                ('rating', models.IntegerField()),
                ('musicianModel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musician.createmusicianmodel')),
            ],
        ),
    ]
