# Generated by Django 5.0.2 on 2024-03-12 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_alter_bookmodel_borrowing_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmodel',
            name='total_copy',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
