# Generated by Django 5.0.2 on 2024-03-14 08:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_bookmodel_borrow_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmodel',
            name='borrow_by',
        ),
        migrations.AddField(
            model_name='bookmodel',
            name='borrow_by',
            field=models.ManyToManyField(blank=True, null=True, related_name='purchased_books', to=settings.AUTH_USER_MODEL),
        ),
    ]
