# Generated by Django 5.0.2 on 2024-03-14 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_remove_bookmodel_borrow_by_bookmodel_borrow_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmodel',
            name='borrow_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
