# Generated by Django 5.0.2 on 2024-03-15 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_bookmodel_returned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmodel',
            name='review',
            field=models.TextField(blank=True, null=True),
        ),
    ]
