# Generated by Django 5.0.2 on 2024-02-26 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profiles',
            name='author',
        ),
    ]
